version: '3.8'

services:
  db:
    container_name: mockp-system_db
    image: postgres
    restart: always
    ports:
      - 2001:5432
    environment:
      POSTGRES_USER: mockp
      POSTGRES_DB: mockp_db
      POSTGRES_PASSWORD: mockp
    volumes:
      - db_data_mockp_system:/var/lib/postgresql/data
volumes:
  db_data_mockp:
