version: '3.8'

services:
  db:
    container_name: library-system_db
    image: postgres
    restart: always
    ports:
      - 2001:5432
    environment:
      POSTGRES_USER: library
      POSTGRES_DB: library_system_db
      POSTGRES_PASSWORD: library
    volumes:
      - db_data_library_system:/var/lib/postgresql/data
volumes:
  db_data_library_system:
